In [1]:
from sklearn.preprocessing import LabelEncoder

In [2]:
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [4]:
# 객체 생성
le = LabelEncoder()

In [6]:
# 학습
le.fit(items)

LabelEncoder()

In [7]:
# 인코딩 실행(변환작업)
labels = le.transform(items)

In [8]:
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [10]:
# 단축형태
le2 = LabelEncoder()
labels = le2.fit_transform(items)
labels


array([0, 1, 4, 5, 3, 3, 2, 2])

In [12]:
labels = LabelEncoder().fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [13]:
le.inverse_transform([2,3,5,0,1])

array(['믹서', '선풍기', '컴퓨터', 'TV', '냉장고'], dtype='<U4')

#### One-hot encoding

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
ohe = OneHotEncoder()
oh_labels = ohe.fit_transform(labels.reshape(-1,1))
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [44]:
from tensorflow.keras.utils import to_categorical
to_categorical(labels)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]], dtype=float32)

### 3. 표준화
- 평균 0, 표준편차 1인 가우시안 표준정규분포

In [46]:
from sklearn.datasets import load_iris
iris = load_iris()

In [47]:
from sklearn.preprocessing import StandardScaler
iris_std = StandardScaler().fit_transform(iris.data)

In [48]:
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

- 로지스틱 회귀

In [49]:
from  sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [55]:
X_train, X_test, y_train, y_test = train_test_split(
    iris_std, iris.target, stratify=iris.target, test_size=0.2, random_state=2023
)
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [56]:
lr.score(X_test,y_test)

0.9666666666666667

#### 정규화
- 최소값, 0 최대값 1

In [58]:
from sklearn.preprocessing import MinMaxScaler
iris_mm =MinMaxScaler().fit_transform(iris.data)
iris_mm

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [61]:
for i in range(4):
  print(iris_mm[:,i].min(), iris_mm[:,i].max())

0.0 1.0
0.0 1.0
0.0 1.0
0.0 1.0


In [62]:
X_train, X_test, y_train, y_test = train_test_split(
    iris_std, iris.target, stratify=iris.target, test_size=0.2, random_state=2023
)
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()